// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type IntegratorConfig struct {
	ID                 uuid.UUID
	ClientID           sql.NullString
	SpID               sql.NullString
	PlazaID            sql.NullString
	Url                sql.NullString
	InsecureSkipVerify sql.NullBool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Log struct {
	ID        uuid.UUID
	Level     sql.NullString
	Message   sql.NullString
	Fields    pqtype.NullRawMessage
	CreatedAt time.Time
}

type SnbConfig struct {
	ID       uuid.UUID
	Endpoint sql.NullString
	Facility sql.NullString
	Device   sql.NullString
}

type User struct {
	ID         uuid.UUID
	Username   sql.NullString
	Password   sql.NullString
	Permission sql.NullString
}
