version: '3.8'
services:
  api-oa-integrator:
    restart: always
    build: ./backend
    container_name: api-oa-integrator
    ports:
      - "1323:1323"
    environment:
      DATABASE_URL: postgres://postgres:a8mJ!4ug2dvj@oa-integrator-db:5432/postgres?sslmode=disable
    depends_on:
      - oa-integrator-db
  oa-dashboard:
    build:
      context: ./web
    container_name: oa-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api-oa-integrator
  oa-integrator-db:
    image: postgres:latest
    container_name: oa-integrator-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a8mJ!4ug2dvj
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
