volumes:
  caddy_data:
  caddy_config:

services:
  backend:
    restart: always
    build:
      context: ./backend
      platforms:
        - linux/amd64
    image: ghcr.io/enctech/api-oa-integrator-backend:0.0.4
    container_name: backend
    platform: linux/amd64
    ports:
      - "127.0.0.1:1323:1323"
    environment:
      - TZ=Asia/Singapore
      - DATABASE_URL=postgres://postgres:a8mJ!4ug2dvj@db:5432/postgres?sslmode=disable
    depends_on:
      - db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  web:
    build:
      context: ./web
      platforms:
        - linux/amd64
    image: ghcr.io/enctech/api-oa-integrator-web:0.0.4
    container_name: web
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a8mJ!4ug2dvj
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /root/api-oa-integrator/db-data:/var/lib/postgresql/data
  caddy:
    build:
      context: ./caddy
    image: caddy:2.9
    container_name: caddy
    restart: unless-stopped
    ports:
      - "127.0.0.1:2019:2019"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CLOUDFLARE_API_TOKEN: tiKE18CWRvRQW-1qXcvuPRKIV8AYhyZiIduQhN6r
    depends_on:
      - backend
      - web
