// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: integrator_site.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addSiteFacility = `-- name: AddSiteFacility :exec
insert into integrator_site_facility (site_id, integrator_config_id, facility)
values ($1, $2, $3)
`

type AddSiteFacilityParams struct {
	SiteID             uuid.UUID
	IntegratorConfigID uuid.UUID
	Facility           string
}

func (q *Queries) AddSiteFacility(ctx context.Context, arg AddSiteFacilityParams) error {
	_, err := q.exec(ctx, q.addSiteFacilityStmt, addSiteFacility, arg.SiteID, arg.IntegratorConfigID, arg.Facility)
	return err
}

const createSite = `-- name: CreateSite :one
insert into integrator_site (id, integrator_config_id, provider_id, client_id, vendor_location_id)
values (gen_random_uuid(), $1, $2, $3, $4)
returning id, integrator_config_id, provider_id, client_id, vendor_location_id, created_at, updated_at
`

type CreateSiteParams struct {
	IntegratorConfigID uuid.UUID
	ProviderID         sql.NullInt32
	ClientID           sql.NullString
	VendorLocationID   sql.NullString
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (IntegratorSite, error) {
	row := q.queryRow(ctx, q.createSiteStmt, createSite,
		arg.IntegratorConfigID,
		arg.ProviderID,
		arg.ClientID,
		arg.VendorLocationID,
	)
	var i IntegratorSite
	err := row.Scan(
		&i.ID,
		&i.IntegratorConfigID,
		&i.ProviderID,
		&i.ClientID,
		&i.VendorLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSitesByConfig = `-- name: DeleteSitesByConfig :exec
delete
from integrator_site
where integrator_config_id = $1
`

// The form submits every site at once, so a save replaces the whole set.
func (q *Queries) DeleteSitesByConfig(ctx context.Context, integratorConfigID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteSitesByConfigStmt, deleteSitesByConfig, integratorConfigID)
	return err
}

const getSiteByConfigAndFacility = `-- name: GetSiteByConfigAndFacility :one
select s.id, s.integrator_config_id, s.provider_id, s.client_id, s.vendor_location_id, s.created_at, s.updated_at
from integrator_site s
         join integrator_site_facility f on f.site_id = s.id
where s.integrator_config_id = $1
  and f.facility = $2
`

type GetSiteByConfigAndFacilityParams struct {
	IntegratorConfigID uuid.UUID
	Facility           string
}

// Which site of this config owns the facility. Unique per config, so at most
// one row can match.
func (q *Queries) GetSiteByConfigAndFacility(ctx context.Context, arg GetSiteByConfigAndFacilityParams) (IntegratorSite, error) {
	row := q.queryRow(ctx, q.getSiteByConfigAndFacilityStmt, getSiteByConfigAndFacility, arg.IntegratorConfigID, arg.Facility)
	var i IntegratorSite
	err := row.Scan(
		&i.ID,
		&i.IntegratorConfigID,
		&i.ProviderID,
		&i.ClientID,
		&i.VendorLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSitesByConfig = `-- name: GetSitesByConfig :many
select s.id, s.integrator_config_id, s.provider_id, s.client_id, s.vendor_location_id, s.created_at, s.updated_at,
       coalesce(
                       array_agg(f.facility order by f.facility)
                       filter (where f.facility is not null),
                       '{}'
       )::varchar[] as facilities
from integrator_site s
         left join integrator_site_facility f on f.site_id = s.id
where s.integrator_config_id = $1
group by s.id
order by s.created_at
`

type GetSitesByConfigRow struct {
	ID                 uuid.UUID
	IntegratorConfigID uuid.UUID
	ProviderID         sql.NullInt32
	ClientID           sql.NullString
	VendorLocationID   sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Facilities         []string
}

func (q *Queries) GetSitesByConfig(ctx context.Context, integratorConfigID uuid.UUID) ([]GetSitesByConfigRow, error) {
	rows, err := q.query(ctx, q.getSitesByConfigStmt, getSitesByConfig, integratorConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSitesByConfigRow{}
	for rows.Next() {
		var i GetSitesByConfigRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegratorConfigID,
			&i.ProviderID,
			&i.ClientID,
			&i.VendorLocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.Facilities),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
