// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countLogs = `-- name: CountLogs :one
select count(*)
from logs
where created_at >= $1
  and created_at <= $2
`

type CountLogsParams struct {
	After  time.Time
	Before time.Time
}

func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.queryRow(ctx, q.countLogsStmt, countLogs, arg.After, arg.Before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :execresult
insert into logs (level, message, fields, created_at)
values ($1, $2, $3, $4)
returning id, level, message, fields, created_at
`

type CreateLogParams struct {
	Level     sql.NullString
	Message   sql.NullString
	Fields    pqtype.NullRawMessage
	CreatedAt time.Time
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (sql.Result, error) {
	return q.exec(ctx, q.createLogStmt, createLog,
		arg.Level,
		arg.Message,
		arg.Fields,
		arg.CreatedAt,
	)
}

const getLogs = `-- name: GetLogs :many
select id, level, message, fields, created_at
from logs
where created_at >= $3
  and created_at <= $4
  and ($5::text = '' or message ilike concat('%', $5::text, '%'))
  and ($6::text = '' or fields::text ilike concat('%', $6::text, '%'))
order by created_at desc
limit $1 offset $2
`

type GetLogsParams struct {
	Limit   int32
	Offset  int32
	After   time.Time
	Before  time.Time
	Message string
	Fields  string
}

func (q *Queries) GetLogs(ctx context.Context, arg GetLogsParams) ([]Log, error) {
	rows, err := q.query(ctx, q.getLogsStmt, getLogs,
		arg.Limit,
		arg.Offset,
		arg.After,
		arg.Before,
		arg.Message,
		arg.Fields,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.Fields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
