// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countLogs = `-- name: CountLogs :one
select count(*)
from logs
where created_at >= $1
  and created_at <= $2
`

type CountLogsParams struct {
	After  time.Time
	Before time.Time
}

func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.queryRow(ctx, q.countLogsStmt, countLogs, arg.After, arg.Before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :execresult
insert into logs (level, message, fields, created_at)
values ($1, $2, $3, $4)
returning id, level, message, fields, created_at
`

type CreateLogParams struct {
	Level     sql.NullString
	Message   sql.NullString
	Fields    pqtype.NullRawMessage
	CreatedAt time.Time
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (sql.Result, error) {
	return q.exec(ctx, q.createLogStmt, createLog,
		arg.Level,
		arg.Message,
		arg.Fields,
		arg.CreatedAt,
	)
}

const createLogs = `-- name: CreateLogs :execresult
insert into logs (level, message, fields, created_at)
select l, m, f, t
from unnest($1::text[]) with ordinality as a(l, i)
         join unnest($2::text[]) with ordinality as b(m, i2) on a.i = b.i2
         join unnest($3::jsonb[]) with ordinality as c(f, i3) on a.i = i3
         join unnest($4::timestamptz[]) with ordinality as d(t, i4) on a.i = i4
returning id, level, message, fields, created_at
`

type CreateLogsParams struct {
	Column1 []string
	Column2 []string
	Column3 []json.RawMessage
	Column4 []time.Time
}

func (q *Queries) CreateLogs(ctx context.Context, arg CreateLogsParams) (sql.Result, error) {
	return q.exec(ctx, q.createLogsStmt, createLogs,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
	)
}

const getLogs = `-- name: GetLogs :many
select id, level, message, fields, created_at
from logs
where message like concat('%', $3::text, '%')
  and fields::text like concat('%', $4::text, '%')
  and created_at >= $5
  and created_at <= $6
order by created_at desc
limit $1 offset $2
`

type GetLogsParams struct {
	Limit   int32
	Offset  int32
	Message string
	Fields  string
	After   time.Time
	Before  time.Time
}

func (q *Queries) GetLogs(ctx context.Context, arg GetLogsParams) ([]Log, error) {
	rows, err := q.query(ctx, q.getLogsStmt, getLogs,
		arg.Limit,
		arg.Offset,
		arg.Message,
		arg.Fields,
		arg.After,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.Fields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
