definitions:
  auth.CreateUserRequest:
    properties:
      password:
        type: string
      permission:
        type: string
      username:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  config.SnbConfig:
    properties:
      devices:
        items:
          type: string
        type: array
      endpoint:
        type: string
      facilities:
        items:
          type: string
        type: array
    type: object
  oa.CancelJobWrapper:
    properties:
      cancel:
        properties:
          reason:
            properties:
              cancelCode:
                type: string
              reasonText:
                type: string
            type: object
        type: object
    type: object
  oa.Configuration:
    properties:
      supportedFunctions:
        items:
          type: string
        type: array
    type: object
  oa.FinalMessageSB:
    properties:
      finalState:
        type: string
      paymentMedia:
        type: string
    type: object
  oa.FinalMessageSBWrapper:
    properties:
      finalMessageSB:
        $ref: '#/definitions/oa.FinalMessageSB'
    type: object
  oa.Job:
    properties:
      jobId:
        properties:
          id:
            type: string
        type: object
      jobType:
        type: string
      mediaDataList:
        properties:
          identifier:
            properties:
              name:
                type: string
            type: object
          mediaType:
            type: string
        type: object
      providerInformation:
        properties:
          provider:
            properties:
              providerId:
                type: string
            type: object
        type: object
      timeAndPlace:
        properties:
          computer:
            properties:
              computerNumber:
                type: string
            type: object
          device:
            properties:
              deviceNumber:
                type: string
              deviceType:
                type: string
            type: object
          facility:
            properties:
              facilityNumber:
                type: string
            type: object
          operator:
            properties:
              operatorNumber:
                type: string
            type: object
          transactionTimeStamp:
            properties:
              timeStamp:
                type: string
            type: object
        type: object
    type: object
  oa.JobWrapper:
    properties:
      job:
        $ref: '#/definitions/oa.Job'
    type: object
  oa.MediaDataWrapper:
    properties:
      mediaData:
        properties:
          hashValue:
            properties:
              value:
                type: string
            type: object
          mediaType:
            type: string
        type: object
    type: object
  oa.VersionRequestWrapper:
    properties:
      version:
        properties:
          configuration:
            $ref: '#/definitions/oa.Configuration'
          entervoVersion:
            type: string
          sbAuthorizationVersion:
            type: string
        type: object
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server OA integrator.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger OA Integrator API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: For user to login into admin
      parameters:
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: user login
      tags:
      - auth
  /auth/user:
    post:
      consumes:
      - application/json
      description: For admin to create new user
      parameters:
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/auth.CreateUserRequest'
      produces:
      - application/json
      responses: {}
      summary: create new user
      tags:
      - auth
  /auth/user/{id}:
    delete:
      consumes:
      - application/json
      description: For admin to delete user
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: delete user
      tags:
      - auth
  /config/snb-config:
    get:
      consumes:
      - application/json
      description: Get configuration required for OA to works.
      parameters:
      - description: Facility
        in: query
        name: facility
        required: true
        type: string
      - description: Device
        in: query
        name: device
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Get config for snb
      tags:
      - config
    post:
      consumes:
      - application/json
      description: Create configuration required for OA to works.
      parameters:
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/config.SnbConfig'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Create config for snb
      tags:
      - config
  /oa/{facility}/{device}/{jobId}:
    post:
      consumes:
      - application/xml
      description: Creates new job and sends the required information as URI and <job>
        element to 3rd party system.
      parameters:
      - description: Facility
        in: path
        name: facility
        required: true
        type: string
      - description: Device
        in: path
        name: device
        required: true
        type: string
      - description: Job ID
        in: path
        name: jobId
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/oa.JobWrapper'
      produces:
      - application/xml
      responses: {}
      summary: S&B creates new job
      tags:
      - oa
  /oa/{facility}/{device}/{jobId}/cancel:
    put:
      consumes:
      - application/xml
      description: This request cancels a running job on the 3rd party side. The job
        is identified by its resource /facility/device/jobid
      parameters:
      - description: Facility
        in: path
        name: facility
        required: true
        type: string
      - description: Device
        in: path
        name: device
        required: true
        type: string
      - description: Job ID
        in: path
        name: jobId
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/oa.CancelJobWrapper'
      produces:
      - application/xml
      responses: {}
      summary: Cancels a running job
      tags:
      - oa
  /oa/{facility}/{device}/{jobId}/finalmessage:
    put:
      consumes:
      - application/xml
      description: This request sends the last message for a job. The job is identified
        by its resources /facility/device/jobid
      parameters:
      - description: Facility
        in: path
        name: facility
        required: true
        type: string
      - description: Device
        in: path
        name: device
        required: true
        type: string
      - description: Job ID
        in: path
        name: jobId
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/oa.FinalMessageSBWrapper'
      produces:
      - application/xml
      responses: {}
      summary: Receive Final Message from S&B
      tags:
      - oa
  /oa/{facility}/{device}/{jobId}/medialist:
    post:
      consumes:
      - application/xml
      description: Creates new media data for an existing job and sends the required
        information as a <mediaData> element to the 3rd party system.
      parameters:
      - description: Facility
        in: path
        name: facility
        required: true
        type: string
      - description: Device
        in: path
        name: device
        required: true
        type: string
      - description: Job ID
        in: path
        name: jobId
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/oa.MediaDataWrapper'
      produces:
      - application/xml
      responses: {}
      summary: Creates new media data
      tags:
      - oa
  /oa/version:
    put:
      consumes:
      - application/xml
      description: get the version and configuration available
      parameters:
      - description: Request Body
        in: body
        name: request
        schema:
          $ref: '#/definitions/oa.VersionRequestWrapper'
      produces:
      - application/xml
      responses: {}
      summary: check version
      tags:
      - oa
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
